[pytest]
log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format=%Y-%m-%d %H:%M:%S

markers =
    smoke: дымовые тесты (критичный функционал)
    regression: регрессионные тесты
    slow: медленные тесты (БД, внешние сервисы)
    api: тесты API
    db: тесты с прямой работой с БД
    negative: негативные сценарии
    positive: позитивные сценарии
    roles: тесты прав доступа
addopts = -v --alluredir=./allure-results
          -o console_output_style=progress